import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/nav";
import { getServerSession } from "next-auth";
import Link from "next/link";
import Logout from "./logout";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html className=" bg-black" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nav/>
        <nav className="w-full bg-black  h-8 shadow-xl ">
          <div className="float-right">
          <div>
          {!!session && <Logout/>  
          }
          {!session && <Link className=" hover:cursor-pointer float-right sm:mr-16 relative text-slate-400 font-bold  shadow-red-700 rounded-3xl px-3 hover:text-red-700" href={'/SignIn'}> Login </Link>}
             </div>
        
          </div>
         
        </nav>
        {children}
      </body>
    </html>
  );
}
